# @format

site_name: TCAT Wiki
site_url: https://taskarcenteratuw.github.io/tcat-wiki/
repo_name: TCAT Wiki on GitHub
repo_url: https://github.com/TaskarCenterAtUW/tcat-wiki
copyright: Copyright &copy; 2025 Taskar Center for Accessible Technology
site_description: Information and guides related to the Taskar Center for Accessible Technology (TCAT) at the University of Washington
theme:
  name: material
  custom_dir: overrides
  font:
    text: Open Sans
  language: en
  direction: ltr
  favicon: resources/images/favicon/tcat/favicon.svg
  logo: resources/images/logo/tcat/logo-light.png
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: custom
      accent: custom
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference mode
      primary: custom
      accent: custom
  features:
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - header.autohide
  icon:
    repo: fontawesome/brands/github
extra_css:
  - resources/stylesheets/extra.css
plugins:
  - meta
  - privacy
  - search
  - social:
      cards_layout_options:
        logo: docs\resources\images\logo\tcat\logo-social.png
  - tags:
      tags_allowed:
        - Internal
        - External
        - Developer
        - User
        - Guide
        - User Manual
        - OSW 0.2
        - OSW 0.3
        - OSW 0.4
  - git-revision-date-localized:
      enable_creation_date: true
      timezone: America/Los_Angeles
  - git-committers:
      repository: TaskarCenterAtUW/tcat-wiki
      branch: main
extra:
  social:
    - name: TCAT on GitHub
      icon: fontawesome/brands/github
      link: https://github.com/TaskarCenterAtUW/
    - name: TCAT on LinkedIn
      icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/taskar-center-for-accessible-technology
    - name: TCAT on YouTube
      icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@taskarcenterstransportatio734
    - name: TCAT on X
      icon: fontawesome/brands/x-twitter
      link: https://x.com/TaskarCenter
    - name: TCAT on FaceBook
      icon: fontawesome/brands/facebook
      link: https://www.facebook.com/TaskarCenter
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
watch:
  - includes
  - overrides
nav:
  - Home: index.md
  - AccessMap:
      - accessmap/index.md
      - User Manual:
          - accessmap/user-manual/index.md
  - AVIV ScoutRoute:
      - aviv-scoutroute/index.md
      - Quests:
          - aviv-scoutroute/quests/index.md
          - Element Query Guide: aviv-scoutroute/quests/element-query.md
          - Element Type Icon Guide: aviv-scoutroute/quests/element-type-icon.md
      - User Manual:
          - aviv-scoutroute/user-manual/index.md
  - Guides List:
      - guides-list/index.md
  - JOSM:
      - josm/index.md
      - Workspaces JOSM Settings Guide: josm/workspaces-josm-settings.md
  - OpenSidewalks:
      - opensidewalks/index.md
      - Schema:
          - opensidewalks/schema/index.md
          - Core Edges in OSW: opensidewalks/schema/core-edges-in-osw.md
          - Custom Points in OSW: opensidewalks/schema/custom-points-in-osw.md
          - OpenSidewalks in OpenStreetMap: opensidewalks/schema/osw-in-osm.md
      - Tasking Manager:
          - opensidewalks/tasking-manager/index.md
          - Task Polygon Automation Guide: opensidewalks/tasking-manager/task-polygon-automation.md
          - User Manual:
              - opensidewalks/tasking-manager/user-manual/index.md
  - Rapid:
      - rapid/index.md
  - TDEI:
      - tdei/index.md
      - Portal:
          - tdei/portal/index.md
          - TDEI Portal Account Registration Guide: tdei/portal/account-registration.md
          - User Manual:
              - tdei/portal/user-manual/index.md
      - TDEI Core:
          - tdei/tdei-core/index.md
  - TDEI Walkshed:
      - tdei-walkshed/index.md
      - User Manual:
          - tdei-walkshed/user-manual/index.md
  - TDEI Workspaces:
      - tdei-workspaces/index.md
      - Workspace Export Guide: tdei-workspaces/workspace-export.md
      - User Manual:
          - tdei-workspaces/user-manual/index.md
          - Workspace Settings: tdei-workspaces/user-manual/workspace-settings.md
  - Workspaces:
      - User Manual:
          - workspaces/user-manual/index.md
  - Contributing: CONTRIBUTING.md
