#region Meta
[project]
version = "5.0.0"
site_name = "The Taskar Center for Accessible Technology"
site_description = "Information and guides related to the Taskar Center for Accessible Technology (TCAT) at the University of Washington."
site_author = "Taskar Center for Accessible Technology"
site_url = "https://taskarcenteratuw.github.io/tcat-wiki/"
copyright = "Copyright &copy; 2026 Taskar Center for Accessible Technology"
extra_css = [
    "stylesheets/extra.css",
    "https://unpkg.com/katex@0/dist/katex.min.css"
]
extra_javascript = [
    "javascripts/extra.js",
    "javascripts/katex.js",
    "https://unpkg.com/katex@0/dist/katex.min.js",
    "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js"
]

#region Theme
[project.theme]
custom_dir = "overrides"
favicon = "resources/images/favicon/tcat/favicon.svg"
language = "en"
logo = "resources/images/logo/tcat/logo-light.png"
features = [
    "announce.dismiss",
    #"content.action.edit",
    #"content.action.view",
    "content.code.annotate",
    "content.code.copy",
    "content.code.select",
    "content.footnote.tooltips",
    "content.tabs.link",
    "content.tooltips",
    #"header.autohide",
    #"navigation.expand",
    #"navigation.footer",
    "navigation.indexes",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    #"navigation.prune",
    "navigation.sections",
    "navigation.tabs",
    #"navigation.tabs.sticky",
    "navigation.top",
    "navigation.tracking",
    #"search.highlight",
    "toc.follow"
    #"toc.integrate"
]

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.font]
text = "Atkinson Hyperlegible Next"
code = "Atkinson Hyperlegible Mono"

[project.theme.icon]
repo = "fontawesome/brands/github"

#region Extensions
[project.markdown_extensions.abbr]
[project.markdown_extensions.admonition]
[project.markdown_extensions.attr_list]
#[project.markdown_extensions.def_list]
#[project.markdown_extensions.footnotes]
[project.markdown_extensions.md_in_html]
[project.markdown_extensions.toc]
title = "On this page:"
permalink = "⚓︎"
permalink_title = "Anchor link to this section"
[project.markdown_extensions.pymdownx.arithmatex]
generic = true
[project.markdown_extensions.pymdownx.betterem]
smart_enable = "all"
[project.markdown_extensions.pymdownx.caret]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.emoji]
emoji_generator = "zensical.extensions.emoji.to_svg"
emoji_index = "zensical.extensions.emoji.twemoji"
[project.markdown_extensions.pymdownx.highlight]
[project.markdown_extensions.pymdownx.inlinehilite]
[project.markdown_extensions.pymdownx.keys]
[project.markdown_extensions.pymdownx.mark]
[project.markdown_extensions.pymdownx.smartsymbols]
[project.markdown_extensions.pymdownx.snippets]
auto_append = [ "includes/abbreviations.md" ]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
    {name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format"}
]
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true
[project.markdown_extensions.pymdownx.tilde]

#region Extras
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/TaskarCenterAtUW/"
[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/company/taskar-center-for-accessible-technology"
[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://www.youtube.com/@taskarcenterstransportatio734"
[[project.extra.social]]
icon = "fontawesome/brands/facebook"
link = "https://www.facebook.com/TaskarCenter"
[[project.extra.social]]
icon = "fontawesome/brands/instagram"
link = "https://www.instagram.com/TaskarCenter/"

#region Navigation
nav = [
    {"Welcome" = "index.md"},
    {"AccessMap" = [
        "accessmap/index.md",
        {"User Manual" = [ "accessmap/user-manual/index.md" ]}
    ]},
    {"AVIV ScoutRoute" = [
        "aviv-scoutroute/index.md",
        {"Quests" = [
            "aviv-scoutroute/quests/index.md",
            {"Element Query Guide" = "aviv-scoutroute/quests/element-query.md"},
            {"Element Type Icon Guide" = "aviv-scoutroute/quests/element-type-icon.md"}
        ]},
        {"User Manual" = [
            "aviv-scoutroute/user-manual/index.md",
            {"Installation" = "aviv-scoutroute/user-manual/installation.md"},
            {"Getting Started" = "aviv-scoutroute/user-manual/getting-started.md"},
            {"Map Interface" = "aviv-scoutroute/user-manual/map-interface.md"},
            {"Completing Quests" = "aviv-scoutroute/user-manual/completing-quests.md"},
            {"Quest Types" = "aviv-scoutroute/user-manual/quest-types.md"},
            {"App Settings" = "aviv-scoutroute/user-manual/app-settings.md"}
        ]}
    ]},
    {"Events" = [
        "events/index.md",
        {"Mny26" = [
            "events/mny26/index.md",
            {"Mapping Guide" = "events/mny26/mapping-guide.md"},
            {"Event Summary" = "events/mny26/report.md"},
            {"Validation Guide" = "events/mny26/validation-guide.md"}
        ]},
        {"Nda Vancouver" = [
            "events/nda-vancouver/index.md",
            {"AccessMap" = "events/nda-vancouver/accessmap.md"},
            {"AVIV ScoutRoute" = "events/nda-vancouver/aviv-scoutroute.md"}
        ]},
        {"Olympia Connected" = [
            "events/olympia-connected/index.md",
            {"Mapping Guide" = "events/olympia-connected/mapping-guide.md"},
            {"Validation Guide" = "events/olympia-connected/validation-guide.md"}
        ]},
        {"Oswmh" = [ "events/oswmh/index.md" ]}
    ]},
    {"JOSM" = [
        "josm/index.md",
        {"Workspaces JOSM Settings Guide" = "josm/workspaces-josm-settings.md"},
        {"User Manual" = [ "josm/user-manual/index.md" ]}
    ]},
    {"OpenSidewalks" = [
        "opensidewalks/index.md",
        {"Schema" = [
            "opensidewalks/schema/index.md",
            {"Core Edges in OSW" = "opensidewalks/schema/core-edges-in-osw.md"},
            {"Custom Points in OSW" = "opensidewalks/schema/custom-points-in-osw.md"},
            {"OpenSidewalks in OpenStreetMap" = "opensidewalks/schema/osw-in-osm.md"}
        ]},
        {"Tasking Manager" = [
            "opensidewalks/tasking-manager/index.md",
            {"Tasking Manager Project List" = "opensidewalks/tasking-manager/project-list.md"},
            {"Task Polygon Automation Guide" = "opensidewalks/tasking-manager/task-polygon-automation.md"},
            {"User Manual" = [ "opensidewalks/tasking-manager/user-manual/index.md" ]}
        ]}
    ]},
    {"OS-CONNECT" = [
        "os-connect/index.md",
        {"Data Viewer" = [
            "os-connect/data-viewer/index.md",
            {"User Manual" = [
                "os-connect/data-viewer/user-manual/index.md",
                {"Interface Overview" = "os-connect/data-viewer/user-manual/interface.md"},
                {"Boundaries" = "os-connect/data-viewer/user-manual/boundaries.md"},
                {"Data" = "os-connect/data-viewer/user-manual/data.md"},
                {"Feedback" = "os-connect/data-viewer/user-manual/feedback.md"}
            ]}
        ]},
        {"Qa Qc" = [
            "os-connect/qa-qc/index.md",
            {"User Manual" = [
                "os-connect/qa-qc/user-manual/index.md",
                {"Data Sources and OS-CONNECT QA/QC Report Structure" = "os-connect/qa-qc/user-manual/structure.md"},
                {"OS-CONNECT QA/QC Report Subsections in Detail" = "os-connect/qa-qc/user-manual/metrics.md"},
                {"Data Infrastructure for QA/QC Report Generation" = "os-connect/qa-qc/user-manual/infrastructure.md"}
            ]}
        ]}
    ]},
    {"Rapid" = [
        "rapid/index.md",
        {"User Manual" = [ "rapid/user-manual/index.md" ]}
    ]},
    {"TDEI" = [
        "tdei/index.md",
        {"Portal" = [
            "tdei/portal/index.md",
            {"User Manual" = [
                "tdei/portal/user-manual/index.md",
                {"TDEI Portal Account Registration Guide" = "tdei/portal/user-manual/account-registration.md"}
            ]}
        ]},
        {"TDEI Core" = [ "tdei/tdei-core/index.md" ]}
    ]},
    {"Walksheds" = [
        "walksheds/index.md",
        {"User Manual" = [ "walksheds/user-manual/index.md" ]}
    ]},
    {"Workspaces" = [
        "workspaces/index.md",
        {"Workspace Export Guide" = "workspaces/workspace-export.md"},
        {"User Manual" = [
            "workspaces/user-manual/index.md",
            {"Workspace Settings" = "workspaces/user-manual/workspace-settings.md"}
        ]}
    ]},
    {"Guides List" = "guides-list/index.md"}
]
